CompileFlags:
  Add: -Wno-unknown-warning-option
  # Remove: [-m*, -f*]

Diagnostics:
  ClangTidy:
    FastCheckFilter: None
    Add:
      - bugprone-*
      - cert-*
      - cppcoreguidelines-*
      - google-*
      - hicpp-*
      - misc-*
      - modernize-*
      - performance-*
      - readability-*
    Remove:
      - android-*
      - boost-*
      - bugprone-easily-swappable-parameters
      - bugprone-exception-escape
      - cert-dcl50-cpp
      - cert-err58-cpp
      - concurrency-*
      - cppcoreguidelines-avoid-non-const-global-variables
      - cppcoreguidelines-init-variables
      - cppcoreguidelines-macro-usage
      - cppcoreguidelines-narrowing-conversions
      - cppcoreguidelines-owning-memory
      - cppcoreguidelines-prefer-member-initializer
      - cppcoreguidelines-pro-bounds-array-to-pointer-decay
      - cppcoreguidelines-pro-bounds-constant-array-index
      - cppcoreguidelines-pro-bounds-pointer-arithmetic
      - cppcoreguidelines-pro-type-reinterpret-cast
      - cppcoreguidelines-pro-type-union-access
      - cppcoreguidelines-pro-type-vararg
      - fuchsia-*
      - google-readability-avoid-underscore-in-googletest-name
      - google-readability-namespace-comments
      - google-runtime-references
      - hicpp-deprecated-headers
      - hicpp-named-parameter
      - hicpp-no-array-decay
      - hicpp-no-assembler
      - hicpp-signed-bitwise
      - hicpp-vararg
      - llvm-header-guard
      - llvm-include-order
      - llvm-namespace-comment
      - misc-no-recursion
      - misc-non-private-member-variables-in-classes
      - misc-unused-parameters
      - modernize-avoid-c-arrays
      - modernize-deprecated-headers
      - modernize-use-default-member-init
      - modernize-use-nodiscard
      - modernize-use-trailing-return-type
      - performance-trivially-destructible
      - readability-container-data-pointer
      - readability-convert-member-functions-to-static
      - readability-function-cognitive-complexity
      - readability-identifier-length
      - readability-magic-numbers
      - readability-make-member-function-const
      - readability-named-parameter
      - readability-qualified-auto
      - readability-redundant-member-init
      - readability-uppercase-literal-suffix
