CompileFlags:
  Add: -Wno-unknown-warning-option
  # Remove: [-m*, -f*]  # NOTE: uncomment these for avr32 and freertos development.

Diagnostics:
  ClangTidy:
    FastCheckFilter: None
    Add:
      - abseil-*
      - bugprone-*
      - cert-*
      - cppcoreguidelines-*
      - google-*
      - hicpp-*
      - llvm-*
      - misc-*
      - modernize-*
      - mpi-*
      - objc-*
      - performance-*
      - portability-*
      - readability-*
    Remove:
      - abseil-string-find-str-contains
      - boost-*
      - bugprone-easily-swappable-parameters
      - bugprone-empty-catch
      - bugprone-exception-escape
      - bugprone-narrowing-conversions
      - bugprone-switch-missing-default-case
      - cert-dcl50-cpp
      - cert-err33-c
      - cert-err58-cpp
      - cert-int09-c
      - cppcoreguidelines-avoid-c-arrays
      - cppcoreguidelines-avoid-magic-numbers
      - cppcoreguidelines-avoid-non-const-global-variables
      - cppcoreguidelines-init-variables
      - cppcoreguidelines-macro-usage
      - cppcoreguidelines-narrowing-conversions
      - cppcoreguidelines-non-private-member-variables-in-classes
      - cppcoreguidelines-owning-memory
      - cppcoreguidelines-pro-bounds-array-to-pointer-decay
      - cppcoreguidelines-pro-bounds-pointer-arithmetic
      - cppcoreguidelines-pro-type-union-access
      - cppcoreguidelines-pro-type-vararg
      - cppcoreguidelines-prefer-member-initializer
      - cppcoreguidelines-pro-type-reinterpret-cast
      - cppcoreguidelines-use-default-member-init
      - google-readability-todo
      - hicpp-avoid-c-arrays
      - hicpp-multiway-paths-covered
      - hicpp-named-parameter
      - hicpp-no-array-decay
      - hicpp-signed-bitwise
      - hicpp-uppercase-literal-suffix
      - hicpp-vararg
      - llvm-header-guard
      - llvm-namespace-comment
      - llvm-qualified-auto
      - misc-header-include-cycle
      - misc-non-private-member-variables-in-classes
      - misc-no-recursion
      - misc-use-internal-linkage
      - modernize-use-default-member-init
      - modernize-use-designated-initializers
      - modernize-use-nodiscard
      - modernize-use-ranges
      - modernize-use-std-print
      - modernize-use-trailing-return-type
      - performance-enum-size
      - readability-avoid-return-with-void-value
      - readability-container-data-pointer
      - readability-convert-member-functions-to-static
      - readability-enum-initial-value
      - readability-function-cognitive-complexity
      - readability-identifier-length
      - readability-magic-numbers
      - readability-make-member-function-const
      - readability-named-parameter
      - readability-qualified-auto
      - readability-redundant-inline-specifier
      - readability-redundant-member-init
      - readability-redundant-casting
      - readability-uppercase-literal-suffix
      - readability-use-std-min-max
